name: CI/CD

on:
  pull_request:
    branches: [ main, master ]
  push:
    branches: [ main, master ]
  workflow_dispatch: {}

env:
  MAVEN_OPTS: -Xmx1024m

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./TourGuide
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          cache-dependency-path: './TourGuide/pom.xml'

      - name: Install local dependencies
        run: |
          mvn -B install:install-file -Dfile=libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
          mvn -B install:install-file -Dfile=libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
          mvn -B install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar

      - name: Compile
        run: mvn -B clean compile

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: compile
    defaults:
      run:
        working-directory: ./TourGuide
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          cache-dependency-path: './TourGuide/pom.xml'

      - name: Install local dependencies
        run: |
          mvn -B install:install-file -Dfile=libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
          mvn -B install:install-file -Dfile=libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
          mvn -B install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar

      - name: Run tests
        run: mvn -B test

  package:
    name: Package
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ./TourGuide
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
          cache-dependency-path: './TourGuide/pom.xml'

      - name: Install local dependencies
        run: |
          mvn -B install:install-file -Dfile=libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
          mvn -B install:install-file -Dfile=libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
          mvn -B install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar

      - name: Package
        run: mvn -B package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tourguide-jar
          path: ./TourGuide/target/*.jar
